apiVersion: v1
kind: Service
metadata:
  name: mysql-clusterip-service
spec:
  type: ClusterIP
  clusterIP: None # This means we are going to use the POD IP address as the service IP address.
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
      name: mysql
  selector:
    app: mysql
