apiVersion: storage.k8s.io/v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 10Gi
