apiVersion: v1
kind: Service
metadata:
  name: user-management-svc
  labels:
    app: user-management
spec:
  type: NodePort
  selector:
    app: user-management
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30001
