apiVersion: v1
kind: ConfigMap
metadata:
  name: user-management-dbcreation-script
data:
  mysql_usermgmt.sql: |
    DROP DATABASE IF EXISTS user_management;
    CREATE DATABASE user_management;
    USE user_management;
    CREATE TABLE users (
      id INT AUTO_INCREMENT PRIMARY KEY,
      email VARCHAR(255) NOT NULL UNIQUE,
      password VARCHAR(255) NOT NULL,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
